# Declare variables
CC = gcc
CFLAGS = -Wall -Werror
SRC_DIR = src
OBJ_DIR = obj
BIN_DIR = bin

# Define the source files and object files for the cliente program
CLIENTE_SRC_FILES = $(wildcard $(SRC_DIR)/cliente*.c)
CLIENTE_OBJ_FILES = $(patsubst $(SRC_DIR)/%.c,$(OBJ_DIR)/%.o,$(CLIENTE_SRC_FILES))

# Define the source files and object files for the server program
SERVER_SRC_FILES = $(wildcard $(SRC_DIR)/server*.c)
SERVER_OBJ_FILES = $(patsubst $(SRC_DIR)/%.c,$(OBJ_DIR)/%.o,$(SERVER_SRC_FILES))

# Define the executable files
CLIENTE_EXECUTABLE = $(BIN_DIR)/cliente
SERVER_EXECUTABLE = $(BIN_DIR)/server

# Default target
all: $(CLIENTE_EXECUTABLE) $(SERVER_EXECUTABLE)

# Link object files into the executables
$(CLIENTE_EXECUTABLE): $(CLIENTE_OBJ_FILES)
	$(CC) $(CFLAGS) $^ -o $@

$(SERVER_EXECUTABLE): $(SERVER_OBJ_FILES)
	$(CC) $(CFLAGS) $^ -o $@

# Compile source files into object files
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c $(SRC_DIR)/assist.h $(SRC_DIR)/assist.c
	$(CC) $(CFLAGS) -c $< -o $@

# Clean up object and executable files
clean:
	rm -f $(OBJ_DIR)/*.o $(CLIENTE_EXECUTABLE) $(SERVER_EXECUTABLE)

# PHONY targets do not represent files
.PHONY: all clean
